### ISSUE TITLE
paper reproduction in gridverse  7x7, 9x9

### ISSUE THREAD

**Issue by SuperCodeAI** [kevslinger/DTQN#13]
Hi,

First of all, I want to commend you on your great idea and thank you for sharing your code.

After reading your paper and being impressed, I have been trying to reproduce the results using your code.

However, after conducting several experiments with the main branch, the performance seems to be unstable.

I have been working with griverse 7x7, 9x9, and other configurations, but there are many cases where the success rate drops sharply.

I found out from the issue board that the version used in the paper is in the 'paper' branch.

Could you please explain any major changes between these two branches?

![image](https://github.com/user-attachments/assets/5bf5cbd5-c148-4187-ac37-56ab504ca593)
![image](https://github.com/user-attachments/assets/f1b68d26-51fe-4159-8de6-6340fa7046d8)

**Comment by kevslinger** [comment]
Hi HakHo,

Thank you for your interest in DTQN! Indeed, if you would like to reproduce the issues from the paper, you should use the `paper` branch (as mentioned in the README). 

If you'd like the know the differences between the `main` and `paper` branches, I recommend looking through the commit history. You can see the `paper` branch is `4 commits ahead, 46 commits behind main`. The major features I worked toward implementing on the `main` branch include adding support for domains which return images as observations (therefore often requiring a different embedding/encoder in order to perform well, and sometimes adding an extra dimension to the observation), and adding a "persistent memory bag". With this bag idea, I tried to learn to keep some observations in context longer than they normally would with the standard FIFO observation queue approach. This bag is by default set off, but it is possible some of the changes to implement these features introduced performance issues for the original domain set from my paper as my focus with these new features was on new, more challenging domains.
